services:
  sict-hybrid-crack-measurement:
    build:
      context: .
    image: sict-hybrid-crack-measurement:python3.13.5-debian12
    container_name: sict-hybrid-crack-measurement
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/sict-hybrid-crack-measurement
      - /tmp/.X11-unix:/tmp/.X11-unix

  sict-hybrid-crack-measurement-gpu:
    extends:
      service: sict-hybrid-crack-measurement
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
